### ISSUE TITLE
Solver code missing?

### ISSUE THREAD

**Issue by CriticalCauchy** [at15/mk-fld#13]
Hi Pinglei Guo,

I came across your mk-fld contribution when I was looking for publications about the M-K method.
The description was promising but I couldn't find any code for FLD calculation. Did I overlook something, are files missing or is _pause(30);_ a placeholder for the missing m-k algorithm?

https://github.com/at15/mk-fld/blob/master/src/solver/fld_solver_main.m
```
% Simulate calc
pause(30);
```

regards
CC

**Comment by at15** [comment]
@CriticalCauchy Hi, you are right, the solver code is missing. This is a rewrote of what I did for my undergraduate thesis in material science back in SJTU, but since I changed my major so this project is no longer maintained. I still have my code for undergraduate thesis and the paper, but  the paper is in Chinese. 

The solver part for FLD is mainly from the following paper, it allows you choose different hardening curve (Swift etc.) and yield model (Hill1948 etc.)

````
@article{butuc2002general,
  title={A more general model for forming limit diagrams prediction},
  author={Butuc, MC and Da Rocha, A Barata and Gracio, JJ and Duarte, J Ferreira},
  journal={Journal of materials processing technology},
  volume={125},
  pages={213--218},
  year={2002},
  publisher={Elsevier},
  type = {J},
}
````

As for FLSD, I followed this paper, but I skipped some hard part and only implemented some easy one, there are some equations I didn't figure out.

````
@article{stoughton2000general,
  title={A general forming limit criterion for sheet metal forming},
  author={Stoughton, Thomas B},
  journal={International Journal of Mechanical Sciences},
  volume={42},
  number={1},
  pages={1--27},
  year={2000},
  publisher={Elsevier},
  type = {J},
}
````

And when you write equations remember to use symbolic programming to generate equations instead of manually write equations (it will be too long for human to handle), also don't calculate using symbolic expressions directly, MATLAB is actually using Maple for the symbolic part, the overhead is pretty high.

**Comment by CriticalCauchy** [comment]
Ok. Thanks for your reply.

**Comment by CriticalCauchy** [comment]
Hi Pinglei Guo,
I'm struggling with building a M-K method matlab script. At the moment, I'm stuck at the transition between Zone A and Zone B, because I don't know how to calculate the missing strain increments delta_eps_nn_B and delta_eps_nt_B.
I don't want to waste your time but if you found some time to look at my code, I'd very much appreciate it.
https://github.com/CriticalCauchy/MK-test

regards
CC
